// Top Sales
export const TOP_SALES_REQUEST = 'TOP_SALES_REQUEST';
export const TOP_SALES_SUCCESS = 'TOP_SALES_SUCCESS';
export const TOP_SALES_FAILURE = 'TOP_SALES_FAILURE';
// Categories
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
// Catalog
export const CATEGORY_CHANGED = 'CATEGORY_CHANGED';
export const CATALOG_ITEMS_REQUEST = 'CATALOG_ITEMS_REQUEST';
export const CATALOG_ITEMS_SUCCESS = 'CATALOG_ITEMS_SUCCESS';
export const CATALOG_ITEMS_FAILURE = 'CATALOG_ITEMS_FAILURE';
export const CATALOG_RESET = 'CATALOG_RESET';
export const CATALOG_GET_MORE = 'CATALOG_GET_MORE';
export const CATALOG_SHOW_NO_MORE = 'CATALOG_SHOW_NO_MORE';
export const CATALOG_OFFSET_INCREMENTED = 'CATALOG_OFFSET_INCREMENTED';
// Search
export const SEARCH_BUTTON_PRESSED = 'SEARCH_BUTTON_PRESSED';
export const SEARCH_FIELD_CHANGED = 'SEARCH_FIELD_CHANGED';
export const SEARCH_CLEARED = 'SEARCH_CLEARED';
